{{- $secretName := .Values.cratedbUserSystemName }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if $secret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "finops-database-handler.fullname" . }}-endpoint
stringData:
  server-url: http://{{ include "finops-database-handler.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}
  username: system
  password: {{ $secret.data.password }}
{{- end }}