apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "finops-database-handler.fullname" . }}-endpoint
stringData:
  server-url: http://{{ include "finops-database-handler.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}
  username: system
  password: |
    {{- $secretName := .Values.cratedb-user-system-name -}}
    {{- $secret := lookup "v1" "Secret" "finops" $secretName -}}
    {{- if $secret.data.password -}}
    {{- $secret.data.password | b64decode -}}
    {{- end -}}